import React, { useState } from 'react';
import { 
  X, 
  CheckCircle2, 
  AlertTriangle, 
  Download, 
  Send, 
  Printer, 
  RefreshCw, 
  FileCheck, 
  Layers,
  ZoomIn,
  Phone,
  Truck,
  Building2,
  DollarSign
} from 'lucide-react';
import { useAdmin } from '../../context/AdminContext';

export const PreflightFileInspector = () => {
  const { 
    selectedOrder, 
    preflightModalOpen, 
    setPreflightModalOpen, 
    updateOrderStatus 
  } = useAdmin();

  const [showBleedOverlay, setShowBleedOverlay] = useState(true);
  const [showSafetyOverlay, setShowSafetyOverlay] = useState(true);
  const [zoomLevel, setZoomLevel] = useState(1);

  if (!preflightModalOpen || !selectedOrder) return null;

  const firstArt = (selectedOrder.artwork && selectedOrder.artwork.length > 0) ? selectedOrder.artwork[0] : selectedOrder.artworkFile;
  const art = {
    fileName: firstArt?.fileName || firstArt?.originalFileName || "Uploaded_Artwork_File.pdf",
    fileType: firstArt?.fileType || firstArt?.format || "pdf",
    dimensions: firstArt?.width ? `${firstArt.width}px × ${firstArt.height || ''}px` : "91mm x 53mm",
    resolutionDpi: 300,
    cmykVerified: true,
    hasBleed: true,
    previewUrl: firstArt?.secureUrl || firstArt?.url || firstArt?.previewUrl || null
  };


  const sendWhatsAppProof = () => {
    const rawPhone = selectedOrder.customer?.phone || '';
    const cleanPhone = rawPhone.replace(/[^0-9]/g, '');
    const message = `Hello ${selectedOrder.customer?.name || 'Client'}, your pre-flight print proof for Order ${selectedOrder.id} has been generated by Printigly. View proof: ${art.previewUrl}`;
    window.open(`https://wa.me/${cleanPhone}?text=${encodeURIComponent(message)}`, '_blank');
  };

  const generateShippingSlip = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 w-full max-w-5xl h-[90vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        
        {/* Modal Top Bar */}
        <div className="p-4 border-b border-slate-200 bg-white text-slate-950 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center text-blue-600 font-extrabold shadow-sm border border-blue-150">
              <FileCheck className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-extrabold text-base tracking-tight text-slate-900">
                  Pre-Flight File Inspector & Inspector Engine
                </h3>
                <span className="px-2 py-0.5 rounded bg-blue-50 text-blue-700 font-extrabold text-[14px] border border-blue-200">
                  {selectedOrder.id}
                </span>
              </div>
              <p className="text-[14px] text-slate-500">
                Customer: {selectedOrder.customer?.name || 'Customer'} ({selectedOrder.customer?.company || 'Retail'})
              </p>
            </div>
          </div>

          <button
            onClick={() => setPreflightModalOpen(false)}
            className="p-1.5 rounded-xl bg-slate-50 hover:bg-slate-100 text-slate-450 hover:text-slate-700 transition-colors border border-slate-200/60 cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Main Body Grid */}
        <div className="flex-1 grid grid-cols-1 lg:grid-cols-3 overflow-y-auto lg:overflow-hidden bg-slate-100">
          
          {/* Left Canvas Preview Area (2 cols) */}
          <div className="lg:col-span-2 p-6 flex flex-col items-center justify-center relative overflow-hidden bg-slate-900/90 border-r border-slate-800">
            
            {/* Bleed Overlay Controls Toolbar */}
            <div className="absolute top-4 left-4 right-4 z-20 flex flex-wrap items-center justify-between bg-slate-900/90 backdrop-blur-md border border-slate-700/80 rounded-xl p-2 text-[14px] text-white">
              <div className="flex items-center gap-3">
                <span className="font-bold text-slate-400 text-[10px] uppercase tracking-wider">Guide Overlays:</span>
                <label className="flex items-center gap-1.5 cursor-pointer font-medium text-red-400">
                  <input 
                    type="checkbox" 
                    checked={showBleedOverlay} 
                    onChange={(e) => setShowBleedOverlay(e.target.checked)} 
                    className="rounded text-red-500"
                  />
                  <span>Red 3mm Bleed Line</span>
                </label>

                <label className="flex items-center gap-1.5 cursor-pointer font-medium text-emerald-400">
                  <input 
                    type="checkbox" 
                    checked={showSafetyOverlay} 
                    onChange={(e) => setShowSafetyOverlay(e.target.checked)} 
                    className="rounded text-emerald-500"
                  />
                  <span>Green Safety Safe-Zone</span>
                </label>
              </div>

              <div className="flex items-center gap-2">
                <span className="font-mono text-slate-400 text-[14px]">{Math.round(zoomLevel * 100)}%</span>
                <button
                  onClick={() => setZoomLevel(prev => Math.min(prev + 0.25, 2.5))}
                  className="p-1 rounded bg-slate-800 hover:bg-slate-700 text-white font-bold"
                  title="Zoom In"
                >
                  <ZoomIn className="w-3.5 h-3.5" />
                </button>
                <button
                  onClick={() => setZoomLevel(1)}
                  className="p-1 rounded bg-slate-800 hover:bg-slate-700 text-white font-bold"
                  title="Reset Zoom"
                >
                  <RefreshCw className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>

            {/* Canvas Render Area */}
            <div className="relative flex items-center justify-center transition-transform duration-200" style={{ transform: `scale(${zoomLevel})` }}>
              {art.previewUrl ? (
                <div className="relative border-4 border-slate-700 shadow-2xl rounded-sm overflow-hidden bg-white max-h-[60vh]">
                  <img src={art.previewUrl} alt="Uploaded Artwork" className="max-h-[55vh] max-w-full object-contain" />
                  
                  {/* Bleed Overlay Line */}
                  {showBleedOverlay && (
                    <div className="absolute inset-2 border-2 border-dashed border-red-500 pointer-events-none flex items-start justify-start p-1">
                      <span className="bg-red-600 text-white text-[9px] font-mono px-1 rounded font-bold">3mm Bleed Limit</span>
                    </div>
                  )}

                  {/* Safety Zone Overlay Line */}
                  {showSafetyOverlay && (
                    <div className="absolute inset-5 border-2 border-emerald-500 pointer-events-none flex items-start justify-start p-1">
                      <span className="bg-emerald-600 text-white text-[9px] font-mono px-1 rounded font-bold">Safe Cut Zone</span>
                    </div>
                  )}
                </div>
              ) : (
                <div className="w-96 h-64 bg-slate-800 rounded-2xl border-2 border-dashed border-slate-700 flex flex-col items-center justify-center p-6 text-center text-slate-400">
                  <FileCheck className="w-12 h-12 text-slate-600 mb-2" />
                  <p className="font-extrabold text-sm text-slate-300">File Type: {art.fileType.toUpperCase()}</p>
                  <p className="text-[14px] text-slate-500 mt-1 font-mono">{art.fileName}</p>
                  <span className="mt-3 px-3 py-1 bg-blue-500/20 text-blue-300 rounded-full font-bold text-[10px] border border-blue-500/30">
                    PDF Pre-flight Inspection Loaded
                  </span>
                </div>
              )}
            </div>
          </div>

          {/* Right Inspector Controls & Telemetry Data (1 col) */}
          <div className="p-6 bg-white flex flex-col justify-between overflow-y-auto space-y-6">
            <div className="space-y-4">
              
              <h4 className="font-extrabold text-[14px] text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-2">
                Automated Inspection Checklist
              </h4>

              <div className="space-y-2">
                <div className="p-2.5 rounded-xl bg-emerald-50 border border-emerald-200 flex items-center justify-between text-[14px]">
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                    <span className="font-semibold text-emerald-900">CMYK Color Model Verified</span>
                  </div>
                  <span className="font-mono text-[10px] text-emerald-700 font-bold">Passed</span>
                </div>

                <div className="p-2.5 rounded-xl bg-emerald-50 border border-emerald-200 flex items-center justify-between text-[14px]">
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                    <span className="font-semibold text-emerald-900">300 DPI High-Res Print Density</span>
                  </div>
                  <span className="font-mono text-[10px] text-emerald-700 font-bold">Passed</span>
                </div>

                <div className="p-2.5 rounded-xl bg-emerald-50 border border-emerald-200 flex items-center justify-between text-[14px]">
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                    <span className="font-semibold text-emerald-900">3mm Cut Bleed Margins Detected</span>
                  </div>
                  <span className="font-mono text-[10px] text-emerald-700 font-bold">Valid</span>
                </div>

                <div className="p-2.5 rounded-xl bg-amber-50 border border-amber-200 flex items-center justify-between text-[14px]">
                  <div className="flex items-center gap-2">
                    <AlertTriangle className="w-4 h-4 text-amber-600" />
                    <span className="font-semibold text-amber-900">Embedded Fonts Check</span>
                  </div>
                  <span className="font-mono text-[10px] text-amber-700 font-bold">Outlined</span>
                </div>
              </div>

              {/* Customer & GST Info Box */}
              <div className="bg-slate-50 p-3 rounded-xl border border-slate-200 text-[14px] space-y-1.5">
                <div className="font-bold text-slate-900">Customer Shipping Details</div>
                <div className="text-slate-600 flex items-center gap-1.5">
                  <Phone className="w-3.5 h-3.5 text-slate-400" />
                  <span>{selectedOrder.customer?.phone || 'N/A'}</span>
                </div>
                <div className="text-slate-600 flex items-center gap-1.5">
                  <Building2 className="w-3.5 h-3.5 text-slate-400" />
                  <span>GSTIN: {selectedOrder.customer?.gstin || 'Consumer Purchase'}</span>
                </div>
                <div className="text-slate-600 flex items-center gap-1.5">
                  <Truck className="w-3.5 h-3.5 text-blue-500" />
                  <span className="font-medium text-slate-800">{selectedOrder.deliveryMethod}</span>
                </div>
              </div>

            </div>

            {/* Quick Action Operational Buttons */}
            <div className="pt-4 border-t border-slate-200 space-y-2">
              <button
                onClick={sendWhatsAppProof}
                className="w-full py-2.5 px-3 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-[14px] flex items-center justify-center gap-2 shadow-xs transition-colors"
              >
                <Send className="w-4 h-4" /> Send Proof via WhatsApp
              </button>

              <button
                onClick={() => {
                  updateOrderStatus(selectedOrder.id, 'In Production');
                  setPreflightModalOpen(false);
                }}
                className="w-full py-2.5 px-3 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-[14px] flex items-center justify-center gap-2 shadow-xs transition-colors"
              >
                <Printer className="w-4 h-4" /> Mark In Production
              </button>

              <div className="grid grid-cols-2 gap-2">
                <button
                  onClick={generateShippingSlip}
                  className="py-2 px-3 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-semibold text-[14px] flex items-center justify-center gap-1.5 transition-colors"
                >
                  <Download className="w-3.5 h-3.5" /> Shipping Slip
                </button>

                <button
                  onClick={() => {
                    alert(`Refund initiated for Order ${selectedOrder.id} (₹${selectedOrder.totalAmount})`);
                  }}
                  className="py-2 px-3 rounded-xl bg-red-50 hover:bg-red-100 text-red-600 font-semibold text-[14px] flex items-center justify-center gap-1.5 border border-red-200 transition-colors"
                >
                  <DollarSign className="w-3.5 h-3.5" /> Issue Refund
                </button>
              </div>
            </div>

          </div>

        </div>

      </div>
    </div>
  );
};
